http:
  path: "/"
  port: 8080

runtime:
  workers: 2
  output: stdout

projects: {}
  # myproject:
  #   ref: "refs/heads/gh-pages"
  #   directory: "/var/www/domain.com"
  #   secret: "xxxxxxxxxxxxxxxxxxxx"
  #   command: "git pull"
