http:
  host: "0.0.0.0"
  port: 8080
  path: "/"

projects:
  myproject:
    action: "push"
    ref: "refs/heads/gh-pages"
    directory: "/tmp"
    command: "touch ./i-was-here.txt"
    timeout: "PT5S"
    secret: "xxxxxxxxxxxxxxxxxxxxxxxxxx"
