package org.alexn.hook

import arrow.core.getOrHandle
import org.apache.commons.codec.digest.HmacAlgorithms
import org.apache.commons.codec.digest.HmacUtils
import java.net.URLEncoder
import java.nio.charset.StandardCharsets.UTF_8
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class EventPayloadTest {
    @Test
    fun `authenticate message with hmac-sha1`() {
        val key = "some-key"
        val json = """
        {
            "action": "some-action",
            "ref": "some-ref",
            "additional": { "field": true }
        }
        """.trimIndent()

        EventPayload
            .authenticateRequest(
                json,
                key,
                "sha1=" + HmacUtils(HmacAlgorithms.HMAC_SHA_1, key).hmacHex(json),
            )
            .getOrHandle { throw it.toException() }
    }

    @Test
    fun `authenticate message with hmac-sha256`() {
        val key = "some-key"
        val json = """
        {
            "action": "some-action",
            "ref": "some-ref",
            "additional": { "field": true }
        }
        """.trimIndent()

        EventPayload
            .authenticateRequest(
                json,
                key,
                "sha256=" + HmacUtils(HmacAlgorithms.HMAC_SHA_256, key).hmacHex(json),
            )
            .getOrHandle { throw it.toException() }
    }

    @Test
    fun `authenticate fails on unknown algorithm`() {
        val key = "some-key"
        val json = """
        {
            "action": "some-action",
            "ref": "some-ref",
            "additional": { "field": true }
        }
        """.trimIndent()

        val r = EventPayload
            .authenticateRequest(
                json,
                key,
                "sha512=" + HmacUtils(HmacAlgorithms.HMAC_SHA_512, key).hmacHex(json),
            )
        assertTrue(r.isLeft(), "Unexpected result: $r")
    }

    @Test
    fun `parse JSON`() {
        val json = """
        {
            "action": "some-action",
            "ref": "some-ref",
            "additional": { "field": true }
        }
        """.trimIndent()

        val received = EventPayload.parseJson(json).getOrHandle { throw it.toException() }
        assertEquals(
            EventPayload(
                action = "some-action",
                ref = "some-ref"
            ),
            received
        )
    }

    @Test
    fun `parse multipart-form data`() {
        val formData =
            "action=${URLEncoder.encode("some action", UTF_8)}&" +
                "ref=${URLEncoder.encode("some ref", UTF_8)}"
        val received = EventPayload.parseFormData(formData).getOrHandle { throw it.toException() }
        assertEquals(
            EventPayload(
                action = "some action",
                ref = "some ref"
            ),
            received
        )
    }

    @Test
    fun `parse fails on invalid JSON`() {
        val yaml = """
        action: some-action
        ref: some-ref
        additional:
            field: true
        """.trimIndent()

        val r = EventPayload.parseJson(yaml)
        assertTrue(r.isLeft(), "Unexpected result: $r")
    }

    @Test
    fun `parse real payload`() {
        val json = """
            {
              "ref": "refs/heads/gh-pages",
              "before": "940fdd916f1417205aaab72025b1cad4fa87ae45",
              "after": "14376968d841606608238de794fc9442d701584f",
              "repository": {
                "id": 3140510,
                "node_id": "MDEwOlJlcG9zaXRvcnkzMTQwNTEw",
                "name": "alexn.org",
                "full_name": "alexandru/alexn.org",
                "private": false,
                "owner": {
                  "name": "alexandru",
                  "email": "alexandru@users.noreply.github.com",
                  "login": "alexandru",
                  "id": 11753,
                  "node_id": "MDQ6VXNlcjExNzUz",
                  "avatar_url": "https://avatars.githubusercontent.com/u/11753?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/alexandru",
                  "html_url": "https://github.com/alexandru",
                  "followers_url": "https://api.github.com/users/alexandru/followers",
                  "following_url": "https://api.github.com/users/alexandru/following{/other_user}",
                  "gists_url": "https://api.github.com/users/alexandru/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/alexandru/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/alexandru/subscriptions",
                  "organizations_url": "https://api.github.com/users/alexandru/orgs",
                  "repos_url": "https://api.github.com/users/alexandru/repos",
                  "events_url": "https://api.github.com/users/alexandru/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/alexandru/received_events",
                  "type": "User",
                  "site_admin": false
                },
                "html_url": "https://github.com/alexandru/alexn.org",
                "description": "The source-code of my personal blog",
                "fork": false,
                "url": "https://github.com/alexandru/alexn.org",
                "forks_url": "https://api.github.com/repos/alexandru/alexn.org/forks",
                "keys_url": "https://api.github.com/repos/alexandru/alexn.org/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/alexandru/alexn.org/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/alexandru/alexn.org/teams",
                "hooks_url": "https://api.github.com/repos/alexandru/alexn.org/hooks",
                "issue_events_url": "https://api.github.com/repos/alexandru/alexn.org/issues/events{/number}",
                "events_url": "https://api.github.com/repos/alexandru/alexn.org/events",
                "assignees_url": "https://api.github.com/repos/alexandru/alexn.org/assignees{/user}",
                "branches_url": "https://api.github.com/repos/alexandru/alexn.org/branches{/branch}",
                "tags_url": "https://api.github.com/repos/alexandru/alexn.org/tags",
                "blobs_url": "https://api.github.com/repos/alexandru/alexn.org/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/alexandru/alexn.org/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/alexandru/alexn.org/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/alexandru/alexn.org/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/alexandru/alexn.org/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/alexandru/alexn.org/languages",
                "stargazers_url": "https://api.github.com/repos/alexandru/alexn.org/stargazers",
                "contributors_url": "https://api.github.com/repos/alexandru/alexn.org/contributors",
                "subscribers_url": "https://api.github.com/repos/alexandru/alexn.org/subscribers",
                "subscription_url": "https://api.github.com/repos/alexandru/alexn.org/subscription",
                "commits_url": "https://api.github.com/repos/alexandru/alexn.org/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/alexandru/alexn.org/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/alexandru/alexn.org/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/alexandru/alexn.org/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/alexandru/alexn.org/contents/{+path}",
                "compare_url": "https://api.github.com/repos/alexandru/alexn.org/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/alexandru/alexn.org/merges",
                "archive_url": "https://api.github.com/repos/alexandru/alexn.org/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/alexandru/alexn.org/downloads",
                "issues_url": "https://api.github.com/repos/alexandru/alexn.org/issues{/number}",
                "pulls_url": "https://api.github.com/repos/alexandru/alexn.org/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/alexandru/alexn.org/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/alexandru/alexn.org/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/alexandru/alexn.org/labels{/name}",
                "releases_url": "https://api.github.com/repos/alexandru/alexn.org/releases{/id}",
                "deployments_url": "https://api.github.com/repos/alexandru/alexn.org/deployments",
                "created_at": 1326146465,
                "updated_at": "2022-09-30T08:41:32Z",
                "pushed_at": 1664984219,
                "git_url": "git://github.com/alexandru/alexn.org.git",
                "ssh_url": "git@github.com:alexandru/alexn.org.git",
                "clone_url": "https://github.com/alexandru/alexn.org.git",
                "svn_url": "https://github.com/alexandru/alexn.org",
                "homepage": "https://alexn.org",
                "size": 241981,
                "stargazers_count": 37,
                "watchers_count": 37,
                "language": "HTML",
                "has_issues": true,
                "has_projects": false,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": true,
                "forks_count": 14,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 0,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [

                ],
                "visibility": "public",
                "forks": 14,
                "open_issues": 0,
                "watchers": 37,
                "default_branch": "main",
                "stargazers": 37,
                "master_branch": "main"
              },
              "pusher": {
                "name": "github-actions[bot]",
                "email": null
              },
              "sender": {
                "login": "github-actions[bot]",
                "id": 41898282,
                "node_id": "MDM6Qm90NDE4OTgyODI=",
                "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                "html_url": "https://github.com/apps/github-actions",
                "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                "type": "Bot",
                "site_admin": false
              },
              "created": false,
              "deleted": false,
              "forced": false,
              "base_ref": null,
              "compare": "https://github.com/alexandru/alexn.org/compare/940fdd916f14...14376968d841",
              "commits": [
                {
                  "id": "14376968d841606608238de794fc9442d701584f",
                  "tree_id": "18883c5732a3659a9de8e833a6097bf9c65a7582",
                  "distinct": true,
                  "message": "docs: update gh-pages",
                  "timestamp": "2022-10-05T15:36:57Z",
                  "url": "https://github.com/alexandru/alexn.org/commit/14376968d841606608238de794fc9442d701584f",
                  "author": {
                    "name": "Alexandru Nedelcu",
                    "email": "noreply@alexn.org",
                    "username": "alexandru"
                  },
                  "committer": {
                    "name": "Alexandru Nedelcu",
                    "email": "noreply@alexn.org",
                    "username": "alexandru"
                  },
                  "added": [

                  ],
                  "removed": [

                  ],
                  "modified": [
                    "404.html",
                    "about/index.html",
                    "blog/2009/02/01/using-best-tools-programming-not-doable/index.html",
                    "blog/2009/02/20/tips-for-creating-voip-dialer/index.html",
                    "blog/2010/05/25/i-hate-null/index.html",
                    "blog/2011/03/24/cross-domain-requests/index.html",
                    "blog/2011/10/23/why-i-find-heroku-suboptimal/index.html",
                    "blog/2011/10/29/how-i-use-flickr/index.html",
                    "blog/2011/11/25/4-books-for-learning-to-design-the-hard-way/index.html",
                    "blog/2011/11/29/earning-money-as-an-amazon-affiliate/index.html",
                    "blog/2011/12/12/android-learning-resources/index.html",
                    "blog/2011/12/15/crawling-the-android-marketplace-155200-apps/index.html",
                    "blog/2012/01/05/blogging-for-hackers/index.html",
                    "blog/2012/01/16/cosine-similarity-euclidean-distance/index.html",
                    "blog/2012/02/09/howto-build-naive-bayes-classifier/index.html",
                    "blog/2012/11/02/scala-functional-programming-type-classes/index.html",
                    "blog/2012/11/07/notes-javascript-development/index.html",
                    "blog/2013/03/14/jvm-multithreading-monitor-locks-visibility/index.html",
                    "blog/2013/05/07/towards-better-atomicreference-scala/index.html",
                    "blog/2013/05/13/getting-started-with-scala/index.html",
                    "blog/2014/10/20/scala-best-practices/index.html",
                    "blog/2015/09/06/monifu-vs-akka-streams/index.html",
                    "blog/2015/12/15/avoid-javaisms-code-smell/index.html",
                    "blog/2016/05/10/monix-task/index.html",
                    "blog/2016/05/15/monix-observable/index.html",
                    "blog/2016/08/25/monix-task-performance/index.html",
                    "blog/2016/11/11/newsblur-bookmarklet/index.html",
                    "blog/2017/01/13/traversable/index.html",
                    "blog/2017/01/16/iterator/index.html",
                    "blog/2017/01/30/asynchronous-programming-scala/index.html",
                    "blog/2017/03/15/fp-inception/index.html",
                    "blog/2017/08/16/automatic-releases-sbt-travis/index.html",
                    "blog/2017/10/11/javascript-promise-leaks-memory/index.html",
                    "blog/2017/10/13/scaladays-copenhagen/index.html",
                    "blog/2017/10/15/functional-programming/index.html",
                    "blog/2017/11/10/minitest-no-crap-scala-library/index.html",
                    "blog/2018/02/12/in-defense-oofp/index.html",
                    "blog/2018/05/06/bifunctor-io/index.html",
                    "blog/2019/08/11/isinstanceof-anti-pattern/index.html",
                    "blog/2019/09/02/blocking-task.scala/index.html",
                    "blog/2019/10/07/async-queue.ts/index.html",
                    "blog/2019/11/22/howto-regexp-replacement-via-function-java-scala/index.html",
                    "blog/2019/11/29/sierpinski.hs/index.html",
                    "blog/2020/02/18/encrypt.sh/index.html",
                    "blog/2020/03/18/send-mail.py/index.html",
                    "blog/2020/04/21/blog-updates/index.html",
                    "blog/2020/04/21/javascript-semaphore/index.html",
                    "blog/2020/05/26/scala-fatal-warnings/index.html",
                    "blog/2020/05/27/future-stack-overflow.scala/index.html",
                    "blog/2020/07/30/from-resource-to-reactivestreams.scala/index.html",
                    "blog/2020/08/03/on-error-retry-loop/index.html",
                    "blog/2020/08/11/flow-sensitive-typing.ts/index.html",
                    "blog/2020/08/13/sbt-fork-debug.sbt/index.html",
                    "blog/2020/08/14/error-hierarchy.scala/index.html",
                    "blog/2020/08/27/safe-password.scala/index.html",
                    "blog/2020/09/10/privilege/index.html",
                    "blog/2020/09/25/flow-processor-to-effect/index.html",
                    "blog/2020/10/05/running-integration-tests.scala/index.html",
                    "blog/2020/10/08/unlawful-effect.scala/index.html",
                    "blog/2020/10/10/when-my-world-vanishes/index.html",
                    "blog/2020/10/12/effect-runtime/index.html",
                    "blog/2020/10/15/generic-ioapp-alternative/index.html",
                    "blog/2020/10/20/block-comments-on-the-web/index.html",
                    "blog/2020/11/11/organize-index-screenshots-ocr-macos/index.html",
                    "blog/2020/11/12/i-like-option-get/index.html",
                    "blog/2020/11/13/list-blog-tags-in-folder/index.html",
                    "blog/2020/11/15/managing-database-migrations-scala/index.html",
                    "blog/2020/11/17/best-practice-for-ordering-comparable/index.html",
                    "blog/2020/11/22/effecttestsuite-scala/index.html",
                    "blog/2020/12/06/execute-shell-command-in-fsharp/index.html",
                    "blog/2020/12/20/no-acceptable-ads/index.html",
                    "blog/2021/01/14/remove-blank-lines/index.html",
                    "blog/2021/01/20/tagless-final-vs-oop/index.html",
                    "blog/2021/01/26/tail-recursive-functions-in-scala/index.html",
                    "blog/2021/02/12/scala-list-secret/index.html",
                    "blog/2021/02/22/countdownlatch-async-dirty/index.html",
                    "blog/2021/02/22/matomo-hosting-via-docker/index.html",
                    "blog/2021/02/26/type-classes-in-scala-3-live-coding-session/index.html",
                    "blog/2021/03/29/atom-rss-feeds-are-the-best-way-to-consume-the-web/index.html",
                    "blog/2021/03/30/tolerance/index.html",
                    "blog/2021/07/18/iterm-open-file-cmd-click-ide-semantic-history/index.html",
                    "blog/2021/08/02/unsafelazyresource-scala/index.html",
                    "blog/2021/08/29/vscode-recommended-extensions-vscode-extensions-json/index.html",
                    "blog/2022/01/22/cleanup-scala-project/index.html",
                    "blog/2022/03/30/focus/index.html",
                    "blog/2022/04/01/blogging/index.html",
                    "blog/2022/04/05/future-monix-typelevel/index.html",
                    "blog/2022/04/09/scala-gitter-discord-mistake/index.html",
                    "blog/2022/04/18/scala-oop-design-sample/index.html",
                    "blog/2022/04/29/free-speech/index.html",
                    "blog/2022/05/11/implicit-vs-scala-3-given/index.html",
                    "blog/2022/05/13/oop-vs-type-classes-part-1-ideology/index.html",
                    "blog/2022/05/23/tracking-effects-in-scala/index.html",
                    "blog/2022/09/01/impressions-on-chrome-brave/index.html",
                    "blog/2022/09/06/limiting-toxic-technology/index.html",
                    "blog/2022/09/07/akka-is-moving-away-from-open-source/index.html",
                    "blog/2022/09/07/free-software-vs-open-source/index.html",
                    "blog/2022/09/09/scala-isnt-fun-anymore/index.html",
                    "blog/2022/09/12/delete-facebook/index.html",
                    "blog/2022/09/13/scripting-with-scala/index.html",
                    "blog/2022/09/19/java-cultural-problem/index.html",
                    "blog/2022/09/21/akka-fork-fud/index.html",
                    "blog/2022/09/21/java-19/index.html",
                    "blog/2022/09/22/proprietary-environments-are-a-trap/index.html",
                    "blog/2022/09/28/the-trouble-with-checked-exceptions-part-2/index.html",
                    "blog/2022/10/03/execute-shell-commands-in-java-scala-kotlin/index.html",
                    "blog/index.html",
                    "blog/page/2/index.html",
                    "blog/page/3/index.html",
                    "blog/page/4/index.html",
                    "blog/page/5/index.html",
                    "blog/page/6/index.html",
                    "blog/tag/akka/index.html",
                    "blog/tag/algorithms/index.html",
                    "blog/tag/android/index.html",
                    "blog/tag/api/index.html",
                    "blog/tag/async/index.html",
                    "blog/tag/asynchrony/index.html",
                    "blog/tag/bash/index.html",
                    "blog/tag/best of/index.html",
                    "blog/tag/best practices/index.html",
                    "blog/tag/blogging/index.html",
                    "blog/tag/books/index.html",
                    "blog/tag/browser/index.html",
                    "blog/tag/cats effect/index.html",
                    "blog/tag/cli/index.html",
                    "blog/tag/cloud/index.html",
                    "blog/tag/concurrency/index.html",
                    "blog/tag/dotnet/index.html",
                    "blog/tag/fp/index.html",
                    "blog/tag/fp/page/2/index.html",
                    "blog/tag/fsharp/index.html",
                    "blog/tag/haskell/index.html",
                    "blog/tag/heroku/index.html",
                    "blog/tag/java/index.html",
                    "blog/tag/javascript/index.html",
                    "blog/tag/jekyll/index.html",
                    "blog/tag/jvm/index.html",
                    "blog/tag/kotlin/index.html",
                    "blog/tag/languages/index.html",
                    "blog/tag/macos/index.html",
                    "blog/tag/mining/index.html",
                    "blog/tag/monix/index.html",
                    "blog/tag/multithreading/index.html",
                    "blog/tag/oop/index.html",
                    "blog/tag/open source/index.html",
                    "blog/tag/opinion/index.html",
                    "blog/tag/perl/index.html",
                    "blog/tag/personal/index.html",
                    "blog/tag/politics/index.html",
                    "blog/tag/programming rant/index.html",
                    "blog/tag/python/index.html",
                    "blog/tag/reactive streams/index.html",
                    "blog/tag/ruby/index.html",
                    "blog/tag/sbt/index.html",
                    "blog/tag/scala/index.html",
                    "blog/tag/scala/page/2/index.html",
                    "blog/tag/scala/page/3/index.html",
                    "blog/tag/scala/page/4/index.html",
                    "blog/tag/self-hosting/index.html",
                    "blog/tag/server/index.html",
                    "blog/tag/shell/index.html",
                    "blog/tag/snippet/index.html",
                    "blog/tag/snippet/page/2/index.html",
                    "blog/tag/testing/index.html",
                    "blog/tag/typelevel/index.html",
                    "blog/tag/typescript/index.html",
                    "blog/tag/video/index.html",
                    "blog/tag/web/index.html",
                    "docs/license/index.html",
                    "docs/privacy-policy/index.html",
                    "feeds/all.xml",
                    "feeds/blog.xml",
                    "feeds/newsletter.xml",
                    "feeds/reddit.xml",
                    "feeds/twitter.xml",
                    "feeds/wiki.xml",
                    "index.html",
                    "sitemap.xml",
                    "subscribe/index.html",
                    "wiki/agile/index.html",
                    "wiki/android/index.html",
                    "wiki/chromium/index.html",
                    "wiki/cloudflare/index.html",
                    "wiki/debian-packages-deb/index.html",
                    "wiki/dedrm/index.html",
                    "wiki/dns-lookup/index.html",
                    "wiki/dns-settings/index.html",
                    "wiki/docker/index.html",
                    "wiki/dotnet/index.html",
                    "wiki/dropbox/index.html",
                    "wiki/emacs/index.html",
                    "wiki/email/index.html",
                    "wiki/excel/index.html",
                    "wiki/firefox/index.html",
                    "wiki/git/index.html",
                    "wiki/github/index.html",
                    "wiki/gnu-screen/index.html",
                    "wiki/haskell/index.html",
                    "wiki/image-formats/index.html",
                    "wiki/index.html",
                    "wiki/iterm/index.html",
                    "wiki/java/index.html",
                    "wiki/json/index.html",
                    "wiki/kafka/index.html",
                    "wiki/macos/index.html",
                    "wiki/mysql/index.html",
                    "wiki/nix/index.html",
                    "wiki/org-mode/index.html",
                    "wiki/postgresql/index.html",
                    "wiki/privacy/index.html",
                    "wiki/python/index.html",
                    "wiki/rss-feeds/index.html",
                    "wiki/rust/index.html",
                    "wiki/teach-kids/index.html",
                    "wiki/tls/index.html",
                    "wiki/tmux/index.html",
                    "wiki/ubuntu-server/index.html",
                    "wiki/unix-shell-cli/index.html",
                    "wiki/vim/index.html",
                    "wiki/web/index.html",
                    "wiki/windows/index.html",
                    "wiki/zshrc-prompt/index.html"
                  ]
                }
              ],
              "head_commit": {
                "id": "14376968d841606608238de794fc9442d701584f",
                "tree_id": "18883c5732a3659a9de8e833a6097bf9c65a7582",
                "distinct": true,
                "message": "docs: update gh-pages",
                "timestamp": "2022-10-05T15:36:57Z",
                "url": "https://github.com/alexandru/alexn.org/commit/14376968d841606608238de794fc9442d701584f",
                "author": {
                  "name": "Alexandru Nedelcu",
                  "email": "noreply@alexn.org",
                  "username": "alexandru"
                },
                "committer": {
                  "name": "Alexandru Nedelcu",
                  "email": "noreply@alexn.org",
                  "username": "alexandru"
                },
                "added": [

                ],
                "removed": [

                ],
                "modified": [
                  "404.html",
                  "about/index.html",
                  "blog/2009/02/01/using-best-tools-programming-not-doable/index.html",
                  "blog/2009/02/20/tips-for-creating-voip-dialer/index.html",
                  "blog/2010/05/25/i-hate-null/index.html",
                  "blog/2011/03/24/cross-domain-requests/index.html",
                  "blog/2011/10/23/why-i-find-heroku-suboptimal/index.html",
                  "blog/2011/10/29/how-i-use-flickr/index.html",
                  "blog/2011/11/25/4-books-for-learning-to-design-the-hard-way/index.html",
                  "blog/2011/11/29/earning-money-as-an-amazon-affiliate/index.html",
                  "blog/2011/12/12/android-learning-resources/index.html",
                  "blog/2011/12/15/crawling-the-android-marketplace-155200-apps/index.html",
                  "blog/2012/01/05/blogging-for-hackers/index.html",
                  "blog/2012/01/16/cosine-similarity-euclidean-distance/index.html",
                  "blog/2012/02/09/howto-build-naive-bayes-classifier/index.html",
                  "blog/2012/11/02/scala-functional-programming-type-classes/index.html",
                  "blog/2012/11/07/notes-javascript-development/index.html",
                  "blog/2013/03/14/jvm-multithreading-monitor-locks-visibility/index.html",
                  "blog/2013/05/07/towards-better-atomicreference-scala/index.html",
                  "blog/2013/05/13/getting-started-with-scala/index.html",
                  "blog/2014/10/20/scala-best-practices/index.html",
                  "blog/2015/09/06/monifu-vs-akka-streams/index.html",
                  "blog/2015/12/15/avoid-javaisms-code-smell/index.html",
                  "blog/2016/05/10/monix-task/index.html",
                  "blog/2016/05/15/monix-observable/index.html",
                  "blog/2016/08/25/monix-task-performance/index.html",
                  "blog/2016/11/11/newsblur-bookmarklet/index.html",
                  "blog/2017/01/13/traversable/index.html",
                  "blog/2017/01/16/iterator/index.html",
                  "blog/2017/01/30/asynchronous-programming-scala/index.html",
                  "blog/2017/03/15/fp-inception/index.html",
                  "blog/2017/08/16/automatic-releases-sbt-travis/index.html",
                  "blog/2017/10/11/javascript-promise-leaks-memory/index.html",
                  "blog/2017/10/13/scaladays-copenhagen/index.html",
                  "blog/2017/10/15/functional-programming/index.html",
                  "blog/2017/11/10/minitest-no-crap-scala-library/index.html",
                  "blog/2018/02/12/in-defense-oofp/index.html",
                  "blog/2018/05/06/bifunctor-io/index.html",
                  "blog/2019/08/11/isinstanceof-anti-pattern/index.html",
                  "blog/2019/09/02/blocking-task.scala/index.html",
                  "blog/2019/10/07/async-queue.ts/index.html",
                  "blog/2019/11/22/howto-regexp-replacement-via-function-java-scala/index.html",
                  "blog/2019/11/29/sierpinski.hs/index.html",
                  "blog/2020/02/18/encrypt.sh/index.html",
                  "blog/2020/03/18/send-mail.py/index.html",
                  "blog/2020/04/21/blog-updates/index.html",
                  "blog/2020/04/21/javascript-semaphore/index.html",
                  "blog/2020/05/26/scala-fatal-warnings/index.html",
                  "blog/2020/05/27/future-stack-overflow.scala/index.html",
                  "blog/2020/07/30/from-resource-to-reactivestreams.scala/index.html",
                  "blog/2020/08/03/on-error-retry-loop/index.html",
                  "blog/2020/08/11/flow-sensitive-typing.ts/index.html",
                  "blog/2020/08/13/sbt-fork-debug.sbt/index.html",
                  "blog/2020/08/14/error-hierarchy.scala/index.html",
                  "blog/2020/08/27/safe-password.scala/index.html",
                  "blog/2020/09/10/privilege/index.html",
                  "blog/2020/09/25/flow-processor-to-effect/index.html",
                  "blog/2020/10/05/running-integration-tests.scala/index.html",
                  "blog/2020/10/08/unlawful-effect.scala/index.html",
                  "blog/2020/10/10/when-my-world-vanishes/index.html",
                  "blog/2020/10/12/effect-runtime/index.html",
                  "blog/2020/10/15/generic-ioapp-alternative/index.html",
                  "blog/2020/10/20/block-comments-on-the-web/index.html",
                  "blog/2020/11/11/organize-index-screenshots-ocr-macos/index.html",
                  "blog/2020/11/12/i-like-option-get/index.html",
                  "blog/2020/11/13/list-blog-tags-in-folder/index.html",
                  "blog/2020/11/15/managing-database-migrations-scala/index.html",
                  "blog/2020/11/17/best-practice-for-ordering-comparable/index.html",
                  "blog/2020/11/22/effecttestsuite-scala/index.html",
                  "blog/2020/12/06/execute-shell-command-in-fsharp/index.html",
                  "blog/2020/12/20/no-acceptable-ads/index.html",
                  "blog/2021/01/14/remove-blank-lines/index.html",
                  "blog/2021/01/20/tagless-final-vs-oop/index.html",
                  "blog/2021/01/26/tail-recursive-functions-in-scala/index.html",
                  "blog/2021/02/12/scala-list-secret/index.html",
                  "blog/2021/02/22/countdownlatch-async-dirty/index.html",
                  "blog/2021/02/22/matomo-hosting-via-docker/index.html",
                  "blog/2021/02/26/type-classes-in-scala-3-live-coding-session/index.html",
                  "blog/2021/03/29/atom-rss-feeds-are-the-best-way-to-consume-the-web/index.html",
                  "blog/2021/03/30/tolerance/index.html",
                  "blog/2021/07/18/iterm-open-file-cmd-click-ide-semantic-history/index.html",
                  "blog/2021/08/02/unsafelazyresource-scala/index.html",
                  "blog/2021/08/29/vscode-recommended-extensions-vscode-extensions-json/index.html",
                  "blog/2022/01/22/cleanup-scala-project/index.html",
                  "blog/2022/03/30/focus/index.html",
                  "blog/2022/04/01/blogging/index.html",
                  "blog/2022/04/05/future-monix-typelevel/index.html",
                  "blog/2022/04/09/scala-gitter-discord-mistake/index.html",
                  "blog/2022/04/18/scala-oop-design-sample/index.html",
                  "blog/2022/04/29/free-speech/index.html",
                  "blog/2022/05/11/implicit-vs-scala-3-given/index.html",
                  "blog/2022/05/13/oop-vs-type-classes-part-1-ideology/index.html",
                  "blog/2022/05/23/tracking-effects-in-scala/index.html",
                  "blog/2022/09/01/impressions-on-chrome-brave/index.html",
                  "blog/2022/09/06/limiting-toxic-technology/index.html",
                  "blog/2022/09/07/akka-is-moving-away-from-open-source/index.html",
                  "blog/2022/09/07/free-software-vs-open-source/index.html",
                  "blog/2022/09/09/scala-isnt-fun-anymore/index.html",
                  "blog/2022/09/12/delete-facebook/index.html",
                  "blog/2022/09/13/scripting-with-scala/index.html",
                  "blog/2022/09/19/java-cultural-problem/index.html",
                  "blog/2022/09/21/akka-fork-fud/index.html",
                  "blog/2022/09/21/java-19/index.html",
                  "blog/2022/09/22/proprietary-environments-are-a-trap/index.html",
                  "blog/2022/09/28/the-trouble-with-checked-exceptions-part-2/index.html",
                  "blog/2022/10/03/execute-shell-commands-in-java-scala-kotlin/index.html",
                  "blog/index.html",
                  "blog/page/2/index.html",
                  "blog/page/3/index.html",
                  "blog/page/4/index.html",
                  "blog/page/5/index.html",
                  "blog/page/6/index.html",
                  "blog/tag/akka/index.html",
                  "blog/tag/algorithms/index.html",
                  "blog/tag/android/index.html",
                  "blog/tag/api/index.html",
                  "blog/tag/async/index.html",
                  "blog/tag/asynchrony/index.html",
                  "blog/tag/bash/index.html",
                  "blog/tag/best of/index.html",
                  "blog/tag/best practices/index.html",
                  "blog/tag/blogging/index.html",
                  "blog/tag/books/index.html",
                  "blog/tag/browser/index.html",
                  "blog/tag/cats effect/index.html",
                  "blog/tag/cli/index.html",
                  "blog/tag/cloud/index.html",
                  "blog/tag/concurrency/index.html",
                  "blog/tag/dotnet/index.html",
                  "blog/tag/fp/index.html",
                  "blog/tag/fp/page/2/index.html",
                  "blog/tag/fsharp/index.html",
                  "blog/tag/haskell/index.html",
                  "blog/tag/heroku/index.html",
                  "blog/tag/java/index.html",
                  "blog/tag/javascript/index.html",
                  "blog/tag/jekyll/index.html",
                  "blog/tag/jvm/index.html",
                  "blog/tag/kotlin/index.html",
                  "blog/tag/languages/index.html",
                  "blog/tag/macos/index.html",
                  "blog/tag/mining/index.html",
                  "blog/tag/monix/index.html",
                  "blog/tag/multithreading/index.html",
                  "blog/tag/oop/index.html",
                  "blog/tag/open source/index.html",
                  "blog/tag/opinion/index.html",
                  "blog/tag/perl/index.html",
                  "blog/tag/personal/index.html",
                  "blog/tag/politics/index.html",
                  "blog/tag/programming rant/index.html",
                  "blog/tag/python/index.html",
                  "blog/tag/reactive streams/index.html",
                  "blog/tag/ruby/index.html",
                  "blog/tag/sbt/index.html",
                  "blog/tag/scala/index.html",
                  "blog/tag/scala/page/2/index.html",
                  "blog/tag/scala/page/3/index.html",
                  "blog/tag/scala/page/4/index.html",
                  "blog/tag/self-hosting/index.html",
                  "blog/tag/server/index.html",
                  "blog/tag/shell/index.html",
                  "blog/tag/snippet/index.html",
                  "blog/tag/snippet/page/2/index.html",
                  "blog/tag/testing/index.html",
                  "blog/tag/typelevel/index.html",
                  "blog/tag/typescript/index.html",
                  "blog/tag/video/index.html",
                  "blog/tag/web/index.html",
                  "docs/license/index.html",
                  "docs/privacy-policy/index.html",
                  "feeds/all.xml",
                  "feeds/blog.xml",
                  "feeds/newsletter.xml",
                  "feeds/reddit.xml",
                  "feeds/twitter.xml",
                  "feeds/wiki.xml",
                  "index.html",
                  "sitemap.xml",
                  "subscribe/index.html",
                  "wiki/agile/index.html",
                  "wiki/android/index.html",
                  "wiki/chromium/index.html",
                  "wiki/cloudflare/index.html",
                  "wiki/debian-packages-deb/index.html",
                  "wiki/dedrm/index.html",
                  "wiki/dns-lookup/index.html",
                  "wiki/dns-settings/index.html",
                  "wiki/docker/index.html",
                  "wiki/dotnet/index.html",
                  "wiki/dropbox/index.html",
                  "wiki/emacs/index.html",
                  "wiki/email/index.html",
                  "wiki/excel/index.html",
                  "wiki/firefox/index.html",
                  "wiki/git/index.html",
                  "wiki/github/index.html",
                  "wiki/gnu-screen/index.html",
                  "wiki/haskell/index.html",
                  "wiki/image-formats/index.html",
                  "wiki/index.html",
                  "wiki/iterm/index.html",
                  "wiki/java/index.html",
                  "wiki/json/index.html",
                  "wiki/kafka/index.html",
                  "wiki/macos/index.html",
                  "wiki/mysql/index.html",
                  "wiki/nix/index.html",
                  "wiki/org-mode/index.html",
                  "wiki/postgresql/index.html",
                  "wiki/privacy/index.html",
                  "wiki/python/index.html",
                  "wiki/rss-feeds/index.html",
                  "wiki/rust/index.html",
                  "wiki/teach-kids/index.html",
                  "wiki/tls/index.html",
                  "wiki/tmux/index.html",
                  "wiki/ubuntu-server/index.html",
                  "wiki/unix-shell-cli/index.html",
                  "wiki/vim/index.html",
                  "wiki/web/index.html",
                  "wiki/windows/index.html",
                  "wiki/zshrc-prompt/index.html"
                ]
              }
            }
        """.trimIndent()

        val parsed = EventPayload
            .parseJson(json)
            .getOrHandle { throw it.toException() }

        assertEquals(
            parsed,
            EventPayload(
                action = null,
                ref = "refs/heads/gh-pages",
            )
        )
    }
}
